### ISSUE TITLE
Re calibrate camera and Sparse SfM

### ISSUE THREAD

**Issue by gkiavash** [gkiavash/Master-Thesis-Structure-from-Motion#10]
In #8, we realized that a bad calibration causes misalignment in final points. For example, bystreets are mostly in the corners of images and with a bad calibration, distortion is more visible in the image's corners. These two could be the reasons for the wrong angles between streets.

So, we need to recalibrate the camera and compare the results with the previous approach.

The new calibration is done by the urban dataset's camera settings, i.e. wide 2.7k. A video of the checkerboard is taken and frames are captured from the video.

Calibration dataset: https://drive.google.com/drive/folders/1JPNSH5TdRLHpwPYL_47eSSVWInH3BGFe?usp=share_link

```yaml

%YAML:1.0
---
width: 2704
height: 1538
K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.3330333496269382e+03, 0., 1.3622385792503271e+03, 0.,
       1.1527953767273623e+03, 7.0502874427578854e+02, 0., 0., 1. ]
D: !!opencv-matrix
   rows: 8
   cols: 1
   dt: d
   data: [ -1.6978217867232040e-01, 8.5511409234161839e-02,
       -1.9370125115926041e-03, -5.9357627885160916e-03,
       -2.7750704009655319e-02, 0., 0., 0. ]

``` 

An example of undistortion:
![scene10141](https://user-images.githubusercontent.com/58342884/211817938-e20dc88c-4987-4b31-b0b9-5cf2fa7ff205.jpg)
![undist_yaml_4](https://user-images.githubusercontent.com/58342884/211817946-e523252f-d938-47ea-b7d0-286084885459.jpg)
