### ISSUE TITLE
Sparse SfM tests

### ISSUE THREAD

**Issue by albertopretto** [gkiavash/Master-Thesis-Structure-from-Motion#8]
For each dataset:
- Perform sparse SfM by using COLMAP with **single camera model** with and without custom calibration (i.e., let COLMAP estimate the camera parameters in the first case, provide the camera parameters to COLMAP in the seconda case)
- For both the  previous reconstruction, execute PP refinement
- Now we have 4 recosntrsction w/o calib parametrs and w/o refinement: try to align each reconstruction to google map, and qualitatively evaluate the reconstructions.

**Comment by gkiavash** [comment]
Here are the calibration parameters used for this task:

```yml

width: 5184
height: 3888
K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 2.2880100739220425e+03, 0., 2.5716169994772490e+03, 0.,
       2.2845293722010042e+03, 1.9205706165878657e+03, 0., 0., 1. ]
D: !!opencv-matrix
   rows: 8
   cols: 1
   dt: d
   data: [ -2.6434196998339271e-01, 9.9571471417386093e-02,
       -2.4160314862664079e-04, -2.2267220647390027e-04,
       -1.9631169477800196e-02, 0., 0., 0. ]

```

The COLMAP bash code to consider these parameters can be found here: 
https://github.com/gkiavash/Master-Thesis-Structure-from-Motion/blob/cdcecff925e424ada3b6328ad2f331d81e51d933/scripts/colmap_sparse.sh#L16

* Note: calibration dataset has different dimensions than SfM dataset. Checkerboard images are captured with 5184*3888 pixels, while SfM images are taken from video frames with 2.7k quality. So, `Cx` and `Cy` parameters in the camera matrix should be changed. That was the reason COLMAP couldn't find the initial pair in our in-person session.
* Link to the calibration images: https://drive.google.com/drive/folders/199WSPGOkQ5wyquNwL-v2gRp1DSO1eXIs?usp=share_link
